export const PERMISSIONS={
    CREATE_USER:"CREATE_USER",
    DELETE_USER:"DELETE_USER",
    CHANGE_USER_STATUS:"CHANGE_USER_STATUS",
    ASSIGN_ROLE:"ASSIGN_ROLE",
    CREATE_RECORDS:"CREATE_RECORDS",
    UPDATE_RECORDS:"UPDATE_RECORDS",
    DELETE_RECORDS:"DELETE_RECORDS",
    VIEW_RECORDS:"VIEW_RECORDS",
    VIEW_SUMMARY:"VIEW_SUMMARY",
    FILTER_RECORDS:"FILTER_RECORDS"
}
